---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2


provisioner:
  name: chef_zero
platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[deep-security-agent::default]
    attributes:
      kitchen: true
      chef-vault:
        databag_fallback: true
      deep-security-agent:

